Repository Sufferal/MindShare, pull requests merged in 2024-01, with the labels that each got.

#24 Task/user profile
  Client/src/app/app.module.ts
  Client/src/app/modules/profile/components/index.ts
  Client/src/app/modules/profile/components/profile-edit-form/profile-edit-form.component.html
  Client/src/app/modules/profile/components/profile-edit-form/profile-edit-form.component.scss
  Client/src/app/modules/profile/components/profile-edit-form/profile-edit-form.component.spec.ts
  Client/src/app/modules/profile/components/profile-edit-form/profile-edit-form.component.ts
  Client/src/app/modules/profile/pages/user-profile/user-profile.component.html
  Client/src/app/modules/profile/pages/user-profile/user-profile.component.scss
  Client/src/app/modules/profile/pages/user-profile/user-profile.component.ts
  Client/src/app/modules/profile/profile.module.ts
  Client/src/app/modules/profile/services/profile.service.ts
  Client/src/server.js
Labels: enhancement

#25 task: fix against brute force attack
  Client/src/app/modules/auth/components/login/login.component.html
  Client/src/app/modules/auth/components/login/login.component.scss
  Client/src/app/modules/auth/components/login/login.component.ts
Labels: fix

#26 feat: authentication
  Client/angular.json
  Client/package-lock.json
  Client/package.json
  Client/src/app/app-routing.module.ts
  Client/src/app/app.module.ts
  Client/src/app/modules/auth/auth-routing.module.ts
  Client/src/app/modules/auth/auth.module.ts
  Client/src/app/modules/auth/components/index.ts
  Client/src/app/modules/auth/components/login/login.component.html
  Client/src/app/modules/auth/components/login/login.component.scss
  Client/src/app/modules/auth/components/login/login.component.spec.ts
  Client/src/app/modules/auth/components/login/login.component.ts
  Client/src/app/modules/auth/components/register/register.component.html
  Client/src/app/modules/auth/components/register/register.component.scss
  Client/src/app/modules/auth/components/register/register.component.spec.ts
  Client/src/app/modules/auth/components/register/register.component.ts
  Client/src/app/modules/auth/models/user.model.ts
  Client/src/app/modules/auth/pages/auth-page/auth-page.component.html
  Client/src/app/modules/auth/pages/auth-page/auth-page.component.scss
  Client/src/app/modules/auth/pages/auth-page/auth-page.component.spec.ts
  Client/src/app/modules/auth/pages/auth-page/auth-page.component.ts
  Client/src/app/modules/auth/pages/index.ts
  Client/src/app/modules/auth/server.js
  Client/src/app/modules/auth/services/auth-api.service.ts
  Client/src/app/modules/auth/users.json
  Client/src/app/modules/auth/utils/register.validator.ts
  Client/src/assets/.gitkeep
  Client/src/assets/fonts/raleway/Raleway-Black.ttf
  Client/src/assets/fonts/raleway/Raleway-BlackItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-Bold.ttf
  Client/src/assets/fonts/raleway/Raleway-BoldItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-ExtraBold.ttf
  Client/src/assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-ExtraLight.ttf
  Client/src/assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-Italic.ttf
  Client/src/assets/fonts/raleway/Raleway-Light.ttf
  Client/src/assets/fonts/raleway/Raleway-LightItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-Medium.ttf
  Client/src/assets/fonts/raleway/Raleway-MediumItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-Regular.ttf
  Client/src/assets/fonts/raleway/Raleway-SemiBold.ttf
  Client/src/assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
  Client/src/assets/fonts/raleway/Raleway-Thin.ttf
  Client/src/assets/fonts/raleway/Raleway-ThinItalic.ttf
  Client/src/assets/fonts/raleway/raleway.scss
  Client/src/assets/img/login.png
  Client/src/assets/scss/main.scss
  Client/src/assets/scss/utilities.scss
  Client/src/assets/scss/variables.scss
  Client/src/environments/environment.development.ts
  Client/src/environments/environment.ts
  Client/src/index.html
Labels: chore

#27 feat: resources
  Client/src/app/app-routing.module.ts
  Client/src/app/app.module.ts
  Client/src/app/modules/auth/components/login/login.component.html
  Client/src/app/modules/auth/components/login/login.component.scss
  Client/src/app/modules/auth/components/login/login.component.ts
  Client/src/app/modules/resource/components/index.ts
  Client/src/app/modules/resource/components/resource/resource.component.html
  Client/src/app/modules/resource/components/resource/resource.component.scss
  Client/src/app/modules/resource/components/resource/resource.component.spec.ts
  Client/src/app/modules/resource/components/resource/resource.component.ts
  Client/src/app/modules/resource/resource-routing.module.ts
  Client/src/app/modules/resource/resource.module.ts
  Client/src/app/modules/shared/components/footer/footer.component.html
  Client/src/app/modules/shared/components/footer/footer.component.scss
  Client/src/app/modules/shared/components/footer/footer.component.spec.ts
  Client/src/app/modules/shared/components/footer/footer.component.ts
  Client/src/app/modules/shared/components/index.ts
  Client/src/app/modules/shared/components/navbar/navbar.component.html
  Client/src/app/modules/shared/components/navbar/navbar.component.scss
  Client/src/app/modules/shared/components/navbar/navbar.component.spec.ts
  Client/src/app/modules/shared/components/navbar/navbar.component.ts
  Client/src/app/modules/shared/shared.module.ts
  Client/src/assets/img/discipline.png
  Client/src/assets/img/emotions.png
  Client/src/assets/img/motivation.png
  Client/src/assets/scss/main.scss
  Client/src/assets/scss/variables.scss
  package-lock.json
Labels: chore

#29 feat: server-setup
  .gitignore
  MindShare.csproj
  MindShare.sln
  Server/Controllers/AuthController.cs
  Server/Controllers/PostController.cs
  Server/Controllers/ServerController.cs
  Server/Controllers/UserController.cs
  Server/Data/ApplicationDbContext.cs
  Server/Domain/PostModel.cs
  Server/Domain/UserModel.cs
  Server/Migrations/20231130074200_initial.Designer.cs
  Server/Migrations/20231130074200_initial.cs
  Server/Migrations/20231202082034_PasswordSalt.Designer.cs
  Server/Migrations/20231202082034_PasswordSalt.cs
  Server/Migrations/20231203170912_PostFix.Designer.cs
  Server/Migrations/20231203170912_PostFix.cs
  Server/Migrations/20240123150555_AccountActivation.Designer.cs
  Server/Migrations/20240123150555_AccountActivation.cs
  Server/Migrations/ApplicationDbContextModelSnapshot.cs
  Server/Program.cs
  Server/Repositories/AuthRepository.cs
  Server/Repositories/PostRepository.cs
  Server/Repositories/UserRepository.cs
  Server/Server.csproj
  Server/Services/AccountActivationService.cs
  Server/Services/AuthService.cs
  Server/Services/EmailService.cs
  Server/Services/HashingService.cs
  Server/Services/PostService.cs
  Server/Services/UserService.cs
  Server/ViewModel/ActivationModel.cs
  Server/ViewModel/LoginModel.cs
  Server/ViewModel/PostModel.cs
  Server/ViewModel/UserModel.cs
  Server/databaseCreation/app.py
  Server/databaseCreation/database.py
  Server/databaseCreation/initDb.py
  Server/instance/mindShareDatabase.db
Labels: enhancement

#31 chore: send user data to profile, add navbar icons
  Client/package-lock.json
  Client/src/app/modules/auth/components/login/login.component.ts
  Client/src/app/modules/auth/services/auth-api.service.ts
  Client/src/app/modules/profile/services/profile.service.ts
  Client/src/app/modules/shared/components/navbar/navbar.component.html
  Client/src/app/modules/shared/components/navbar/navbar.component.scss
  Client/src/favicon.ico
  Client/src/server.js
  Server/instance/mindShareDatabase.db
Labels: chore

#32 Add account activation message page.
  Client/src/app/modules/auth/auth-routing.module.ts
  Client/src/app/modules/auth/auth.module.ts
  Client/src/app/modules/auth/pages/acc-activation-page/acc-activation-page.component.html
  Client/src/app/modules/auth/pages/acc-activation-page/acc-activation-page.component.scss
  Client/src/app/modules/auth/pages/acc-activation-page/acc-activation-page.component.spec.ts
  Client/src/app/modules/auth/pages/acc-activation-page/acc-activation-page.component.ts
  Client/src/app/modules/auth/pages/index.ts
Labels: chore

#34 fix: add user data to 2FA return message
  Server/Controllers/AuthController.cs
  Server/Services/AuthService.cs
Labels: fix

#35 feat: add html-activation-page
  .gitignore
  Server/Controllers/AuthController.cs
  Server/Program.cs
  Server/Services/AuthService.cs
  Server/Services/EmailService.cs
  Server/activation.html
Labels: enhancement

#36 feat: add 2fa frontend
  Client/src/app/modules/auth/auth-routing.module.ts
  Client/src/app/modules/auth/auth.module.ts
  Client/src/app/modules/auth/components/login/login.component.ts
  Client/src/app/modules/auth/components/two-factor-auth/two-factor-auth.component.html
  Client/src/app/modules/auth/components/two-factor-auth/two-factor-auth.component.scss
  Client/src/app/modules/auth/components/two-factor-auth/two-factor-auth.component.spec.ts
  Client/src/app/modules/auth/components/two-factor-auth/two-factor-auth.component.ts
  Client/src/app/modules/auth/services/auth-api.service.ts
  Client/src/app/modules/profile/components/profile/profile.component.html
  Client/src/app/modules/profile/components/profile/profile.component.scss
  Client/src/app/modules/profile/components/profile/profile.component.ts
  Client/src/app/modules/profile/pages/user-profile/user-profile.component.scss
  Client/src/app/modules/profile/services/profile.service.ts
Labels: enhancement

#38 feat: email validation
  Client/src/app/modules/auth/auth.module.ts
  Client/src/app/modules/auth/components/activation-modal/activation-modal.component.html
  Client/src/app/modules/auth/components/activation-modal/activation-modal.component.scss
  Client/src/app/modules/auth/components/activation-modal/activation-modal.component.spec.ts
  Client/src/app/modules/auth/components/activation-modal/activation-modal.component.ts
  Client/src/app/modules/auth/components/login/login.component.html
  Client/src/app/modules/auth/components/login/login.component.ts
  Client/src/app/modules/auth/components/register/register.component.ts
  Client/src/app/modules/auth/components/two-factor-auth/two-factor-auth.component.ts
  Client/src/app/modules/profile/components/profile/profile.component.ts
Labels: enhancement

#39 chore: apply better styles
  Client/src/app/modules/posts/components/comments-create-form/comments-create-form.component.html
  Client/src/app/modules/posts/components/comments-create-form/comments-create-form.component.scss
  Client/src/app/modules/posts/components/posts-list/posts-list.component.scss
  Client/src/app/modules/posts/pages/feed/feed.component.scss
  Client/src/app/modules/profile/components/profile/profile.component.html
  Client/src/app/modules/profile/components/profile/profile.component.scss
  Client/src/app/modules/profile/pages/user-profile/user-profile.component.html
  Client/src/app/modules/profile/profile.module.ts
  Client/src/app/modules/shared/components/footer/footer.component.html
  Client/src/app/modules/shared/components/navbar/navbar.component.html
  Client/src/app/modules/shared/components/navbar/navbar.component.scss
  Client/src/app/modules/shared/shared.module.ts
  Server/activation.html
Labels: chore

#40 chore: add more records
  Client/src/app/modules/resource/components/resource/resource.component.ts
  Client/src/assets/img/posts/hiking.jpg
  Client/src/assets/img/posts/lightweight.jpg
  Client/src/assets/img/posts/meme_1.png
  Client/src/assets/img/posts/meme_2.png
  Client/src/assets/img/posts/pfp.jpg
  Client/src/assets/img/posts/python.png
  Client/src/assets/img/posts/witcher.jpg
  Client/src/assets/img/resources/discipline.png
  Client/src/assets/img/resources/emotions.png
  Client/src/assets/img/resources/motivation.png
  Client/src/server.js
Labels: chore

#41 docs: update readme
  Client/src/assets/img/pages/login.png
  Client/src/assets/img/pages/posts.png
  Client/src/assets/img/pages/profile.png
  Client/src/assets/img/pages/register.png
  Client/src/assets/img/pages/resources.png
  README.md
Labels: documentation
